Vagrant.configure '2' do |config|
  config.vm.box = 'centos/7'
  config.vm.synced_folder './', '/vagrant'
  config.vm.hostname = 'sonarqube'
  config.vm.network 'forwarded_port', guest: 9000, host: 9000, hostip: '127.0.0.1'
  config.vm.network 'private_network', ip: '192.168.56.10'
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 1024
  end
end
