Vagrant.configure '2' do |config|
  config.vm.box = 'centos/7'
  config.vm.hostname = 'manager'
  config.vm.network 'private_network', ip: '192.168.56.15'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 2048
  end
  config.vm.network 'forwarded_port', guest: 80, host: 80
  config.vm.network 'forwarded_port', guest: 6443, host: 6443
end
