Vagrant.configure '2' do |config|
  config.vm.provision 'shell', inline: <<-EOF
    echo "Configuring manager host"
  EOF
  config.vm.define 'manager' do |manager| # Define specific machine
    manager.vm.box = 'centos/7'
    manager.vm.hostname = 'manager'
    manager.vm.provision 'shell', path: 'provision.sh'
    manager.vm.network 'private_network', ip: '192.168.56.2'
    manager.vm.synced_folder '.', '/vagrant',
                             type: 'nfs',
                             mount_options: ['tcp', 'vers=4']
    manager.vm.network 'forwarded_port', guest: 80, host: 8090
  end

  config.vm.define 'workerApp' do |worker_app|
    worker_app.vm.box = 'centos/7'
    worker_app.vm.hostname = 'workerApp'
    worker_app.vm.provision 'shell', path: 'provision.sh'
    worker_app.vm.network 'private_network', ip: '192.168.56.3'
    worker_app.vm.synced_folder './app', '/vagrant',
                                type: 'nfs',
                                mount_options: ['tcp', 'vers=4']
  end

  config.vm.define 'workerDb' do |db|
    db.vm.box = 'centos/7'
    db.vm.hostname = 'workerDb'
    db.vm.provision 'shell', path: 'provision.sh'
    db.vm.network 'private_network', ip: '192.168.56.4'
    db.vm.synced_folder './db', '/vagrant',
                        type: 'nfs',
                        mount_options: ['tcp', 'vers=4']
  end
end
