Vagrant.configure '2' do |config|
  config.vm.box = 'centos/7'
  config.vm.synced_folder './', '/vagrant', mount_options: ['tcp', 'vers=4']
  config.vm.hostname = 'jenkins'
  config.vm.network 'forwarded_port', guest: 8080, host: 9080, hostip: '127.0.0.1'
  config.vm.network 'private_network', ip: '192.168.56.11'
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 1024
  end
end
